signalement_index:
    path:     /
    defaults: { _controller: "BlogBundle:Signalement:index" }
    methods:  GET

signalement_show:
    path:     /{id}/show
    defaults: { _controller: "BlogBundle:Signalement:show" }
    methods:  GET

signalement_new:
    path:     /new
    defaults: { _controller: "BlogBundle:Signalement:new" }
    methods:  [GET, POST]

signalement_edit:
    path:     /{id}/edit
    defaults: { _controller: "BlogBundle:Signalement:edit" }
    methods:  [GET, POST]

signalement_delete:
    path:     /{id}/delete
    defaults: { _controller: "BlogBundle:Signalement:delete" }
    methods:  [GET, POST]

signalement_delete_article:
    path:     /{id}/delete/article
    defaults: { _controller: "BlogBundle:Signalement:deleteArticle" }
    methods:  [GET, POST]

signalement_delete_commentaire:
    path:     /{id}/delete/commentaire
    defaults: { _controller: "BlogBundle:Signalement:deleteCommentaire" }
    methods:  [GET, POST]

signalement_delete_user:
    path:     /{id}/delete/user
    defaults: { _controller: "BlogBundle:Signalement:deleteUser" }
    methods:  [GET, POST]    