BlogBundle\Entity\ThemeOfficiel:
    type: entity
    table: null
    repositoryClass: BlogBundle\Repository\ThemeOfficielRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        theme:
            type: string
            length: '50'
            unique: true
            
    manyToMany:
        themeArticles:
            targetEntity: Article
            inversedBy: themes

    
    lifecycleCallbacks: { }
    
